#pragma once

enum component_id
{
	COMPONENT_CONTROLLABLE_PHYSICS = 1,
	COMPONENT_RENDER = 2,
	COMPONENT_SIMPLE_PHYSICS = 3,
	COMPONENT_CHARACTER = 4,
	COMPONENT_SCRIPT = 5,
	COMPONENT_BOUNCER = 6,
	COMPONENT_DESTRUCTIBLE = 7,

	COMPONENT_SKILL = 9,
	COMPONENT_VENDOR = 16,
	COMPONENT_INVENTORY = 17,
	COMPONENT_RIGID_BODY_PHANTOM_PHYSICS = 20,

	COMPONENT_COLLECTIBLE = 23,
	COMPONENT_MOVING_PLATFORM = 25,
	COMPONENT_PET = 26,

	COMPONENT_VEHICLE_PHYSICS = 30,
	COMPONENT_SCRIPTED_ACTIVITY = 39,

	COMPONENT_PHANTOM_PHYSICS = 40,
	COMPONENT_MODEL = 42,
	COMPONENT_REBUILD = 48,
	COMPONENT_SWITCH = 49,

	COMPONENT_BASE_COMBAT_AI = 60,
	COMPONENT_MODULE_ASSEMBLY = 61,
	COMPONENT_TRIGGER = 69,

	COMPONENT_RACING_CONTROL = 71,
	COMPONENT_EXHIBIT = 75,

	COMPONENT_Component_107 = 107,
	COMPONENT_108 = 108
};
